# Copyright 2025 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build bykeeb with ZMK Studio'
on: workflow_dispatch
jobs:
  build-left:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["bykeeb_left"]'
      snippet: '["studio-rpc-usb-uart"]'
  build-right:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["bykeeb_right"]'
      snippet: '["studio-rpc-usb-uart"]'
